name: Java CI Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Java environment
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # Step 3: Build the project with Maven
    - name: Build with Maven
      run: mvn clean install

    # Step 4: Run the HelloWorld program
    - name: Run HelloWorld
      run: java -cp target/classes com.example.HelloWorld
